# docker-compose.prod.yml
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn bradrice.wsgi:application --bind 0.0.0.0:8009
    volumes:
      - /var/www/html/bradrice/static:/home/app/web/static/
      - /var/www/html/bradrice/media:/home/app/web/media/
    ports:
      - 8009:8009
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    restart: always
    image: postgres:16
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data_prod:
